nomad-xyz/monorepo

- packages/multi-provider/src/provider.ts
- packages/multi-provider/src/utils.ts
- packages/multi-provider/tests/index.test.ts
- packages/sdk-bridge/tests/index.test.ts
- packages/sdk/tests/index.test.ts
Changes to multi-provider & sdks extracted from #15
> refactor: improve resolution and error handling in multi-provider

- yarn.lock
Updated yarn lock file since it needs to be committed
> fix: update yarn lock file

- packages/sdk-bridge/package.json
- packages/sdk-govern/package.json
- packages/sdk/package.json
- yarn.lock
> chore: bump sdk package config dependency to 0.1.0-rc.6

- packages/sdk-bridge/package.json
- packages/sdk-govern/package.json
- packages/sdk/package.json
> chore: bump sdk package versions for release

- LICENSE-APACHE
- LICENSE-MIT
> chore: add license files

- packages/sdk-bridge/changelog.md
- packages/sdk-bridge/package.json
- packages/sdk/changelog.md
- packages/sdk/package.json
sdk: `2.0.0-rc.4`
sdk-bridge: `1.0.0-rc.4`
> release: bumped sdk and sdk-bridge -- added changelogs

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- Add a contributing doc, 
- move some info from repo root readme to contibuting
- Add a PR template
> docs: contributing and pr template

- package.json
- packages/new-deploy/config/development/config.json
- packages/new-deploy/config/development/overrides.json
- packages/new-deploy/scripts/deploy.ts
- packages/new-deploy/src/bridge/BridgeContracts.ts
- packages/new-deploy/src/core/CoreContracts.ts
- Deploy contracts to testnets
- add logging 
- fix outputting verification
Closes #126 
closes #117
> development deploys: kovan, rinkeby, xDai

- packages/multi-provider/src/index.ts
- packages/multi-provider/src/provider.ts
- packages/multi-provider/src/utils.ts
- packages/new-deploy/package.json
- packages/new-deploy/scripts/deploy.ts
- packages/new-deploy/src/DeployContext.ts
- packages/new-deploy/src/bridge/BridgeContracts.ts
- packages/new-deploy/src/core/CoreContracts.ts
- packages/sdk-bridge/src/BridgeContext.ts
- packages/sdk-govern/src/index.ts
- packages/sdk/src/NomadContext.ts
- packages/sdk/src/error.ts
- packages/sdk/tests/index.test.ts
- yarn.lock
> refactor: callbatch instead of tx array

- packages/new-deploy/changelog.md
- packages/new-deploy/src/DeployContext.ts
- packages/new-deploy/src/bridge/BridgeContracts.ts
- packages/new-deploy/src/changelog.md
- packages/new-deploy/src/core/CoreContracts.ts
https://github.com/nomad-xyz/monorepo/issues/119 Current checks a very basic
Added more core and bridge checks, so we are on a safe side when we deploy for new networks
> Feature: added core and bridge checks

- .gitignore
- foundry.toml
- packages/contracts-bridge/.gitignore
- packages/contracts-core/.gitignore
- packages/contracts-router/.gitignore
- Groundwork for foundry-based verification & testing
- Make a root level foundry.toml with profiles for each solidity package
- [n/a] Added Tests
- [n/a] Updated CHANGELOG.md for the appropriate package
> prep work for foundry usage

- packages/sdk-bridge/src/bridgeEvents.ts
- packages/sdk-govern/src/governanceEvents.ts
Bad import in sdk-bridge and sdk-govern broke yarn build 😬 
Correct to a package import
> fix: correct import from contracts-core

- packages/new-deploy/changelog.md
- packages/new-deploy/package.json
- packages/sdk-bridge/changelog.md
- packages/sdk-bridge/package.json
- packages/sdk-govern/changelog.md
- packages/sdk-govern/package.json
- packages/sdk/changelog.md
- packages/sdk/package.json
- yarn.lock
> chore: bump configuration dependency, update changelogs

- CONTRIBUTING.md
- packages/sdk/tests/index.test.ts
Published to npm, directions in `CONTRIBUTING.md` were out-of-date with what we've discussed in [slack](https://nomad-xyz.slack.com/archives/C02TSDESV0A/p1647550925134439?thread_ts=1647543677.076249&cid=C02TSDESV0A)
Update docs
> update: npm publish docs

- packages/new-deploy/scripts/verify.ts
couple nits :)
- error if no etherscan key
- load environment from file
- comment about how lazy I am
> refactor: cleanup verify script

- packages/new-deploy/changelog.md
- packages/new-deploy/src/core/CoreContracts.ts
Watcher checks used to mix up remote with local watchers. 
Replace local watchers with remote in core checks
> fix: core check for watcher

- packages/new-deploy/changelog.md
- packages/new-deploy/package.json
- packages/sdk-bridge/changelog.md
- packages/sdk-bridge/package.json
- packages/sdk-govern/changelog.md
- packages/sdk-govern/package.json
- packages/sdk/changelog.md
- packages/sdk/package.json
- yarn.lock
Need to update configuration package across sdk related packages and release sdk related packages
Update configuration across all sdk packages.
Update sdk related package version + changelogs.
> release: update sdk, sdk-bridge, sdk-govern with new config version

- packages/indexer/package.json
- packages/sdk-bridge/changelog.md
- packages/sdk-bridge/package.json
- packages/sdk-govern/changelog.md
- packages/sdk-govern/package.json
- packages/sdk/changelog.md
- packages/sdk/package.json
Prep sdk packages for release with updated configuration. Linked to https://github.com/nomad-xyz/monorepo/discussions/223
Prep sdk packages for release with updated configuration
> release: bump package version and update changelog

- CONTRIBUTING.md
- packages/new-deploy/config/overrides-development.json
- packages/new-deploy/config/overrides-production.json
- had Foundry installation issues, originally didn't know how to solve
- add a link to Foundry troubleshooting guide, which had the answer to my question
- add overrides for avalanche and evmos testnet
> add Foundry troubleshooting + add overrides

- packages/new-deploy/changelog.md
- packages/new-deploy/package.json
- packages/sdk-bridge/changelog.md
- packages/sdk-bridge/package.json
- packages/sdk-govern/changelog.md
- packages/sdk-govern/package.json
- packages/sdk/changelog.md
- packages/sdk/package.json
- yarn.lock
Need to update packages with new configuration package version
Update packages with new configuration package version
> chore: bump configuration to v0.1.0-rc.15

- packages/sdk-bridge/changelog.md
- packages/sdk-bridge/package.json
- packages/sdk-govern/changelog.md
- packages/sdk-govern/package.json
- packages/sdk/changelog.md
- packages/sdk/package.json
- yarn.lock
Need to update the config to v0.1.0-rc.16
Update the config to v0.1.0-rc.16
> chore: bump config to v0.1.0-rc.16 for sdk/sdk-bridge/sdk-govern

- packages/sdk-bridge/changelog.md
- packages/sdk-bridge/package.json
- packages/sdk-bridge/src/BridgeContext.ts
Getting several "Out of Gas" errors.  Bumping gas limit by 10%
> fix: bump gas limit

- packages/sdk-bridge/changelog.md
- packages/sdk-bridge/package.json
- packages/sdk-bridge/src/BridgeContext.ts
Get us through the night with no more "Out of gas" transactions
> fix: increase gas more

- packages/indexer/prisma/migrations/20220426164906_confirm_at/migration.sql
- packages/indexer/prisma/schema.prisma
- packages/indexer/src/api/index.ts
- packages/indexer/src/core/consumerV2.ts
- packages/indexer/src/core/indexer.ts
- packages/indexer/src/core/orchestrator.ts
> fix: unknown destination statistic

- packages/indexer/src/api/index.ts
- packages/indexer/src/core/consumer.ts
> More graphql queries

- packages/deploy/changelog.md
- packages/deploy/package.json
- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
- yarn.lock
Hard code gas limit for sendNative
Solve out of gas error when sending native tokens
> Erinhales/sdk bridge rc.13

- packages/sdk-bridge/package.json
- packages/sdk-govern/package.json
- packages/sdk/package.json
- yarn.lock
Updated configuration package and Bumped: 
```
@nomad-xyz/sdk:2.0.0-rc.14
@nomad-xyz/sdk-bridge:1.0.0-rc.14
@nomad-xyz/sdk-govern:1.0.0-rc.14
```
> feat(release): bumped SDK packages

- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/package.json
- packages/sdk-govern/CHANGELOG.md
- packages/sdk-govern/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
latest npm sdk related packages were published incorrectly 
re-publish npm sdk related packages correctly with the latest changes from main
> release: bump package versions and update changelogs

- CONTRIBUTING.md
Prevent bad packages published to npm
Update contributing docs to specifically note what not to do (publish from the package folder directly)
> chore: update contributing docs

- CONTRIBUTING.md
Currently, the setup instructions in contributing.md is a red herring. Until the one-button local env setup is complete, there is no simple "yarn bootstrap" that will simply install all dependencies
Detailing all steps to install dependencies and to build / test deploy contracts.
> Improved setup instructions in contributing.md

- packages/contracts-bridge/contracts/TokenRegistry.sol
- packages/contracts-core/contracts/Home.sol
- packages/contracts-core/contracts/Replica.sol
- packages/contracts-router/contracts/XAppConnectionClient.sol
Address doc issues from QS report
- [n/a] Added Tests
- [n/a (non-functional)] Updated CHANGELOG.md for the appropriate package
> docs: address QS report docs

- packages/contracts-bridge/contracts/BridgeRouter.sol
- packages/contracts-bridge/contracts/TokenRegistry.sol
- packages/contracts-bridge/contracts/vendored/OZERC20.sol
- packages/contracts-core/contracts/Replica.sol
- packages/contracts-core/contracts/Version0.sol
- packages/contracts-core/contracts/XAppConnectionManager.sol
- packages/contracts-core/contracts/governance/GovernanceMessage.sol
- packages/contracts-core/contracts/governance/GovernanceRouter.sol
- packages/contracts-core/contracts/upgrade/UpgradeBeacon.sol
Fix QSP best practices that we're gonna fix
> fix: QS Best practice

- packages/deploy/CHANGELOG.md
- packages/deploy/src/bridge/BridgeContracts.ts
- packages/deploy/src/core/CoreContracts.ts
- packages/deploy/src/utils.ts
We don't want to throw deploy checks during the actual deploy, but rather collect them all into a list and if there are any throw that list
The solution could be found in the Motivation section
> Deploy checks collect errors in place of throwing

- yarn.lock
Build on main is broken due to the yarn.lock not being up to date
Run yarn to update the yarn.lock
> chore: fix build

- .github/workflows/indexer-docker.yml
- packages/indexer/Dockerfile
To make @kekonen's life easier and speed up build process (current 20min)
Add docker build to ci
> Added docker build ci for indexer

- packages/indexer/.env.example
- packages/indexer/src/main.ts
We want to define a port to serve prometheus metrics.
We define that port in a .env file and read it in the app
> Metrics port env variable

- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/package.json
- packages/sdk-bridge/src/BridgeContext.ts
Needed to support https://github.com/nomad-xyz/nomad-app/issues/110 
Allow max amount and cut a new release. h/t to @ErinHales for explaining the solution to me
> release: support infinite token approval

- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/package.json
- packages/sdk-bridge/src/BridgeContext.ts
https://github.com/nomad-xyz/nomad-app/pull/366#issuecomment-1145532495
Subtract a bit from the max safe integer
> fix: infinite token approval + bump version and update changelog

- packages/sdk/CHANGELOG.md
> fix: forgot to commit the changelog

- packages/indexer/CHANGELOG.md
- packages/indexer/docker-compose.rpi.yml
- packages/indexer/docker-compose.yml
- packages/indexer/src/api/index.ts
- packages/indexer/src/core/api.ts
- packages/indexer/src/core/consumerV2.ts
- packages/indexer/src/core/indexer.ts
- packages/indexer/src/core/metrics.ts
- packages/indexer/src/core/utils.ts
- packages/indexer/src/tokens/index.ts
We want to know how many blocks are to tip for each of indexers
Added a metric into prometheus
> Metric blocks to target

- packages/multi-provider/CHANGELOG.md
- packages/multi-provider/README.md
- packages/multi-provider/package.json
- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/README.md
- packages/sdk-bridge/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/README.md
- packages/sdk/package.json
Update readmes for sdk/sdk/multi-provider with examples/links
Npm readme severely lacking.  Examples are nice to point people to.
do the thing
> documentation: sdk readmes

- packages/sdk-govern/package.json
> bump sdk-govern version

- packages/indexer/CHANGELOG.md
- packages/indexer/Dockerfile
- packages/indexer/docker-compose.rpi.yml
- packages/indexer/docker-compose.yml
- packages/indexer/load-tests/README.md
- packages/indexer/load-tests/transaction-history.ts
- packages/indexer/package.json
- packages/indexer/src/api/index.ts
- packages/indexer/src/api/routes.ts
- packages/indexer/src/api/utils.ts
- packages/indexer/src/config.ts
- packages/indexer/src/core/db.ts
- packages/indexer/src/core/index.ts
- packages/indexer/src/core/indexer.ts
- packages/indexer/src/core/orchestrator.ts
- packages/indexer/src/core/redis.ts
- packages/indexer/src/main.ts
- packages/indexer/src/tokens/index.ts
- packages/indexer/tsconfig.json
Noticed we were using environment variables with defaults in a few different places
A config file to hold all config variables with the default values in there for other files to import.
> feat: add config file for all dotenv environment variables

- packages/indexer/src/core/consumerV2.ts
> fix: wrong log level

- packages/contracts-bridge/CHANGELOG.md
- packages/contracts-bridge/package.json
- packages/contracts-core/CHANGELOG.md
- packages/contracts-core/package.json
- packages/contracts-router/CHANGELOG.md
- packages/contracts-router/package.json
- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/package.json
- packages/sdk-govern/CHANGELOG.md
- packages/sdk-govern/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
- packages/sdk/src/NomadContext.ts
- yarn.lock
> update: contract versions

- packages/deploy/scripts/domain.ts
> feat: add back script to calculate domain number

- packages/contracts-bridge/CHANGELOG.md
- packages/contracts-bridge/contracts/BridgeRouter.sol
Bridge functionality was harder to read and harder to extend because it was in mono-functions 
Break functionality into smaller helper functions to clarify the steps involved in token bridging and set the bridge up for extended functionality
> refactor: debit tokens / credit tokens

- packages/indexer/CHANGELOG.md
- packages/indexer/README.md
- packages/indexer/docker-compose.yml
Had a bunch of todos in the readme
Filled in the todos
> chore: update indexer readme and fix docker-compose scripts

- packages/sdk/CHANGELOG.md
> update: changelog

- foundry.toml
> fix: remove offline config from foundry

- packages/contracts-bridge/contracts/test/BridgeMessage.t.sol
- packages/contracts-bridge/contracts/test/utils/BridgeTest.sol
there are too many warnings when compiling tests @odyslam smdh
Address them :)
also fix a test that was doing nothing
> fix: reduce compiler warnings and fix non-functional test

- packages/sdk/src/api.ts
- packages/sdk/src/messages/NomadMessage.ts
Forgot to get the correct indexer url in the status PR
> fix: get api url

- packages/indexer/load-tests/get-events.ts
- packages/indexer/load-tests/utils.ts
- packages/indexer/package.json
- packages/indexer/src/core/indexer.ts
Starting to use indexer for getting events and wanna make sure it can handle extended load
Write a load test. Ran this locally and kept an eye out on the grafana charts. Things seemed fine.
> feat: add basic load test for getting events

- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/package.json
- packages/sdk-govern/CHANGELOG.md
- packages/sdk-govern/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
- packages/sdk/src/messages/NomadMessage.ts
- packages/sdk/src/messages/types.ts
Error fetching proof
fix the thing
fix MessageStatus enum
> fix: get proof

- packages/contracts-core/contracts/test/Home.t.sol
- packages/contracts-core/contracts/test/Replica.t.sol
- packages/contracts-core/contracts/test/harnesses/HomeHarness.sol
- packages/contracts-core/contracts/test/utils/NomadTest.sol
need tests
tests, apart from `doubleUpdate` which is probably going to be removed in the near future
> unit-tests: Home.sol

- packages/contracts-bridge/contracts/BridgeMessage.sol
- packages/contracts-bridge/contracts/BridgeRouter.sol
Apparently, at some point `contracts-bridge` got out of sync with prettier 
Run prettier on `contracts-bridge`
> run prettier on contracts-bridge

- packages/contracts-core/contracts/Replica.sol
Details in the hack root cause analysis here: https://medium.com/nomad-xyz-blog/nomad-bridge-hack-root-cause-analysis-875ad2e5aacd
- `acceptableRoot(0x00)` should always be `false`
- `initialize` should not set `confirmAt(0x00)` moving forward
> fix: zero root is not acceptableRoot

- scripts/install-deps.sh
Get the latest goodies from forge-std
Update the commit hash that we are using in the script --> change the SHA256 of the script --> invalidate old cache in GH CI --> Install and cache latest version by running script
> chore: update running version of forge-strd

- packages/contracts-core/contracts/test/utils/MerkleTest.sol
> fix: MerkleTest hex conversion

- .github/workflows/local-env-release.yml
Adding a release workflow to upload the local environment package to npmjs's artifact repository. 
Added a singular github actions workflow that runs tests plus `npm release`
> Add manual triggered workflow releasing local environment

- .github/workflows/local-env-release.yml
- packages/local-environment/package.json
Fixing the versioning for local-environment and fixing up the publish script. Should publish now
Realized that the `npm publish` command needed to be local to the local-environment package directory, so I fixed that in the workflow.
> bugfix: fixing release workflow and version for local-environment 

- .github/workflows/local-env-release.yml
Testing github actions is a bit of a slog. Found one last bug plus a few optimizations on the commands we're running. 
After updating the flow I realized that running the `yarn version` command in the pipeline can lead to some unexpected behavior later, so I'm going to remove it in lieu of releasing the version thats in the branch at the time.
> bugfix: final local-environment release changes

- packages/local-environment/src/actor.ts
- packages/local-environment/src/agent.ts
- packages/local-environment/src/domain.ts
- packages/local-environment/src/network.ts
- packages/local-environment/src/nomadenv.ts
- packages/local-environment/tests/common.ts
- packages/local-environment/tests/sendTokenCase.int.test.ts
- packages/local-environment/tests/sendTokensCase.ts
- packages/local-environment/tests/start.ts
Just to make it nicer.
* Removed hardcoded ports for agents
* made networks clonable (prerequisite for deploying on the same network)
* small stuff
> LE small adjustments

- .gitignore
- package.json
- packages/chain-ops/.gitignore
- packages/contracts-bridge/.gitignore
- packages/contracts-bridge/package.json
- packages/contracts-core/.gitignore
- packages/contracts-core/package.json
- packages/contracts-router/.gitignore
- packages/contracts-router/package.json
- packages/deploy/.gitignore
- packages/deploy/jest.config.js
- packages/deploy/package.json
- packages/local-environment/.gitignore
- packages/local-environment/jest.config.ts
- packages/local-environment/package.json
- packages/multi-provider/.gitignore
- packages/multi-provider/jest.config.js
- packages/multi-provider/package.json
- packages/sdk-bridge/.gitignore
- packages/sdk-bridge/jest.config.js
- packages/sdk-bridge/package.json
- packages/sdk-govern/.gitignore
- packages/sdk-govern/jest.config.js
- packages/sdk-govern/package.json
- packages/sdk/.gitignore
- packages/sdk/jest.config.js
- packages/sdk/package.json
- scripts/coverage-report.sh
- monorepo wide`yarn coverage`
- code coverage for all contracts* packages (it requires forge, lcov)
- coverage is generated in: `coverage/<package>/index.html`
- @prestwich @anna-carroll let me know if you want to commit the lcov report to the repo
cc @Imti in case coverage is added for other packages as well
> feat(yarn coverage)

- packages/multi-provider/jest.config.js
- packages/multi-provider/package.json
- packages/multi-provider/src/utils.ts
- packages/multi-provider/tests/index.test.ts
- packages/multi-provider/tests/utils.test.ts
- packages/sdk-bridge/package.json
- packages/sdk-govern/package.json
- packages/sdk/package.json
- packages/sdk/tests/index.test.ts
- packages/sdk/tests/message.test.ts
Remembered that I started adding tests a while back and fixed some issues with coverage
Add better test coverage for sdk code.  This mostly covers multi-provider package which is a dependency of the sdk
> add: more multi-provider test coverage

- packages/contracts-bridge/contracts/test/Encoding.t.sol
Test Encoding.sol
Encoding.t.sol
> feat: Fuzzing tests for Encoding.sol

- packages/contracts-bridge/CHANGELOG.md
- packages/contracts-bridge/package.json
- packages/contracts-core/CHANGELOG.md
- packages/contracts-core/package.json
- packages/contracts-router/CHANGELOG.md
- packages/contracts-router/package.json
Prep contract packages for a 2.0.0 release
> chore: prep contract packages for a 2.0.0 release

- foundry.toml
- package.json
- packages/contracts-ops/.gitignore
- packages/contracts-ops/.prettierrc
- packages/contracts-ops/.solhint.json
- packages/contracts-ops/CHANGELOG.md
- packages/contracts-ops/README.md
- packages/contracts-ops/contracts/Placeholder.sol
- packages/contracts-ops/package.json
- yarn.lock
Create a home for foundry-based maintenance scripts
A contracts-ops package 🎉
> feature: contracts-ops package

- packages/contracts-bridge/CHANGELOG.md
- packages/contracts-bridge/contracts/mocks/MockAccountant.sol
- packages/contracts-core/contracts/test/utils/MerkleTest.sol
Enable UI testing of recovery flows
A mock accountant that implements most basic flows
> feat: mock accountant for testing recovery UI

- packages/contracts-core/contracts/test/UpgradeBeacon.t.sol
- packages/contracts-core/contracts/test/UpgradeBeaconController.t.sol
- packages/contracts-core/contracts/test/UpgradeBeaconProxy.t.sol
- packages/contracts-core/contracts/test/utils/MockBeacon.sol
- packages/contracts-core/contracts/test/utils/MockBeaconNotAddr.sol
- packages/contracts-core/contracts/test/utils/MockBeaconRevert.sol
- packages/contracts-core/contracts/test/utils/MockImpl.sol
- packages/contracts-core/contracts/test/utils/UpgradeTest.sol
- UpgradeBeacon.t.sol
- UpgradeBeaconController.t.sol
- UpgradeBeaconProxy.t.sol
> feat: /upgrade unit-testing

- packages/contracts-ops/contracts/CallBatch.sol
Some code in `contracts-ops` didn't have prettier run
Run prettier
> chore: prettier

- packages/sdk-bridge/src/BridgeContext.ts
Corrects the mock accountant address on Goerli
> fix: correct mock staging accountant address

- packages/contracts-core/contracts/test/UpgradeBeaconProxy.t.sol
Fuzz test wuz broke because vm.assume happened before contract was deployed
Fix fuzz test
> patch: fuzz test vm.assume order

- packages/contracts-bridge/CHANGELOG.md
- packages/contracts-bridge/contracts/accountants/NFTAccountant.sol
- packages/contracts-ops/CHANGELOG.md
- packages/contracts-ops/contracts/CallBatch.sol
- packages/contracts-ops/contracts/scripts/DeployAccountant.s.sol
As part of reboot process, need to deploy & configure an upgradable NFTAccountant
Implement forge script to do so
> forge script: deploy upgradable NFTAccountant

- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/src/index.ts
> fix: expose bridge contract accountant types

- packages/contracts-ops/contracts/Config.sol
- packages/contracts-ops/contracts/scripts/DeployAccountant.s.sol
- packages/contracts-ops/contracts/test/utils/INomadProtocol.sol
Precedent to load all values necessary to deploy the protocol did not yet extend to Accountant configuration.
Add Accountant configuration to Config.sol in keeping with its addition to config package
> Add fundsRecipient and accountantOwner via Config.sol

- packages/contracts-bridge/CHANGELOG.md
- packages/contracts-bridge/package.json
- packages/contracts-core/CHANGELOG.md
- packages/contracts-core/package.json
- packages/contracts-router/CHANGELOG.md
- packages/contracts-router/package.json
Prep contracts packages for a 2.1.0-rc.0 release
> chore: prep contracts packages for release

- .gitignore
- packages/contracts-bridge/contracts/test/utils/MockHome.sol
- packages/contracts-core/contracts/test/GovernanceRouter.t.sol
- packages/contracts-core/contracts/test/harnesses/GovernanceRouterHarness.sol
- packages/contracts-core/contracts/test/utils/GoodXapps.sol
- packages/contracts-core/contracts/test/utils/MockXAppConnectionManager.sol
> test: Unit and Fuzzing tests for GovernanceRouter

- packages/contracts-ops/contracts/Config.sol
- packages/contracts-ops/contracts/scripts/DeployAccountant.s.sol
- packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
- packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
- packages/contracts-ops/contracts/test/utils/INomadProtocol.sol
> Chore: refactor config getters

- packages/contracts-ops/contracts/CallBatch.sol
- packages/contracts-ops/contracts/JsonWriter.sol
- packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
- packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
- local and remote calls will be output to a different files, as nesting is not supported by current json output lib
> feat: Batch support for remote and local calls at the same time

- packages/contracts-ops/contracts/scripts/DeployAccountant.s.sol
> refactor: separate DeployAccountant logic from script runner

- packages/contracts-ops/contracts/scripts/DeployAccountant.s.sol
> fix: valid JSON

- packages/contracts-ops/contracts/CallBatch.sol
- packages/contracts-ops/contracts/Config.sol
- packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
- packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
> patch: miscellaneous fixes / usability improvements while running forge scirpt

- .gitignore
Forge outputs details of transactions submitted to mainnet. We don't want these to be tracked in git
gitignore
> gitignore forge broadcast outputs

- packages/contracts-ops/contracts/Config.sol
- packages/contracts-ops/contracts/scripts/DeployImplementations.s.sol
- packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
- packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
- packages/contracts-ops/contracts/test/utils/INomadProtocol.sol
To Upgrade the protocol, we must deploy fresh implementations of each contract before creating governance transactions
Deploy implementations via forge script
> feat: deploy implementations for upgrade

- packages/contracts-ops/contracts/scripts/DeployImplementations.s.sol
- packages/contracts-ops/contracts/scripts/InitializeImplementations.s.sol
Want to reduce potential messy chain state & false alarm bug reports by initializing implementations
Add initialize implementations on top of existing deploy script
> feat: deploy option which adds initialize

- packages/contracts-ops/CHANGELOG.md
- packages/contracts-ops/README.md
- packages/contracts-ops/contracts/Config.sol
- packages/contracts-ops/contracts/scripts/UpgradeCallBatches.s.sol
To realise an upgrade (and update the implementation address of the beacons) we need to execute some governance call batches, 
Build a script that reads an **updated** configuration file (meaning that it has the new implementations) and produce the required call batches in a JSON file
> Feat: Upgrade Callbatches

- packages/contracts-ops/contracts/scripts/DeployImplementations.s.sol
- packages/contracts-ops/contracts/scripts/InitializeImplementations.s.sol
We don't want to manually update the config with the new implementation addresses
The upgrade script will update in-place the config file. After every invocation, the config file will update its implementation addresses for the domain that just got deployed.
> feat: replace in-place the config implementation values

- foundry.toml
- package.json
- packages/contracts-core/contracts/test/Home.t.sol
- packages/contracts-core/contracts/test/NomadBase.t.sol
- packages/contracts-core/contracts/test/Replica.t.sol
- packages/contracts-core/contracts/test/utils/NomadTest.sol
- packages/contracts-ops/CHANGELOG.md
- packages/contracts-ops/README.md
- packages/contracts-ops/contracts/CallBatch.sol
- packages/contracts-ops/contracts/Config.sol
- packages/contracts-ops/contracts/scripts/DeployAccountant.s.sol
- packages/contracts-ops/contracts/scripts/DeployImplementations.s.sol
- packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
- packages/contracts-ops/contracts/scripts/InitializeImplementations.s.sol
- packages/contracts-ops/contracts/scripts/Reboot.s.sol
- packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
- packages/contracts-ops/contracts/scripts/UpgradeCallBatches.s.sol
- packages/contracts-ops/contracts/test/Reboot.t.sol
Want mainnet fork tests for all of the components of the reboot scripts together.
Create a reboot fork test
> test: reboot fork test setup

- packages/contracts-core/contracts/test/Replica.t.sol
- packages/contracts-ops/contracts/CallBatch.sol
- packages/contracts-ops/contracts/Config.sol
- packages/contracts-ops/contracts/scripts/DeployAccountant.s.sol
- packages/contracts-ops/contracts/scripts/DeployImplementations.s.sol
- packages/contracts-ops/contracts/scripts/EnrollReplica.s.sol
- packages/contracts-ops/contracts/scripts/InitializeImplementations.s.sol
- packages/contracts-ops/contracts/scripts/RotateUpdater.s.sol
- packages/contracts-ops/contracts/scripts/UpgradeCallBatches.s.sol
- packages/contracts-ops/contracts/test/Reboot.t.sol
> test: Replica fork test

- packages/contracts-core/contracts/test/Home.t.sol
- packages/contracts-core/contracts/test/NomadBase.t.sol
- packages/contracts-core/contracts/test/Replica.t.sol
- packages/contracts-core/contracts/test/utils/NomadTest.sol
- packages/contracts-ops/contracts/test/Reboot.t.sol
> test: Home fork tests

- packages/contracts-core/contracts/test/Replica.t.sol
- packages/contracts-core/contracts/test/utils/NomadTest.sol
- packages/contracts-ops/contracts/test/Reboot.t.sol
- packages/contracts-ops/contracts/test/RebootHome.t.sol
- packages/contracts-ops/contracts/test/RebootReplica.t.sol
Race condition in foundry spinning up fork tests was fixed; tests can now be refactored more cleanly into their own files
Do the thing :)
> refactor: fork tests in own files

- packages/contracts-core/contracts/test/GovernanceRouter.t.sol
- packages/contracts-core/contracts/test/Home.t.sol
- packages/contracts-core/contracts/test/NomadBase.t.sol
- packages/contracts-core/contracts/test/Replica.t.sol
- packages/contracts-core/contracts/test/utils/NomadTest.sol
- packages/contracts-ops/contracts/scripts/UpgradeCallBatches.s.sol
- packages/contracts-ops/contracts/test/RebootHome.t.sol
- packages/contracts-ops/contracts/test/RebootReplica.t.sol
…ected
Want to ensure fork tests are being set up and run as expected
Remove some unnecessary state vars as there are many inherited contracts. 
Add some assertions as guard rails.
> tweaks to home and replica fork tests

- packages/contracts-core/contracts/test/utils/NomadTest.sol
> feature: more test utils in NomadTest

- packages/contracts-bridge/contracts/test/BridgeRouter.t.sol
- packages/contracts-bridge/contracts/test/BridgeRouterBase.t.sol
- packages/contracts-bridge/contracts/test/Encoding.t.sol
- packages/contracts-bridge/contracts/test/EthereumBridgeRouter.t.sol
- packages/contracts-bridge/contracts/test/TokenRegistry.t.sol
- packages/contracts-bridge/contracts/test/utils/BridgeTest.sol
> make bridge tests env independent via pranks

- packages/contracts-core/contracts/test/GovernanceRouter.t.sol
- packages/contracts-core/contracts/test/utils/MockXAppConnectionManager.sol
- packages/contracts-core/contracts/test/utils/NomadTest.sol
- packages/contracts-ops/contracts/test/Reboot.t.sol
- packages/contracts-ops/contracts/test/RebootGovernanceRouter.t.sol
> governance router fork tests

- packages/contracts-bridge/contracts/test/BridgeRouterBase.t.sol
- packages/contracts-ops/contracts/test/RebootBridgeRouter.t.sol
- packages/contracts-ops/contracts/test/RebootEthereumBridgeRouter.t.sol
> Add fork setup for bridgerouter tests

- packages/contracts-bridge/contracts/test/BridgeRouter.t.sol
- packages/contracts-bridge/contracts/test/BridgeRouterBase.t.sol
- packages/contracts-bridge/contracts/test/NFTAccountant.t.sol
- packages/contracts-bridge/contracts/test/NFTRecoveryAccountant.t.sol
- packages/contracts-bridge/contracts/test/harness/NFTAccountantHarness.sol
- packages/contracts-bridge/contracts/test/utils/AccountantTest.sol
- packages/contracts-bridge/contracts/test/utils/BridgeTest.sol
- packages/contracts-core/contracts/test/GovernanceRouter.t.sol
- packages/contracts-ops/contracts/test/RebootBridgeRouter.t.sol
- packages/contracts-ops/contracts/test/RebootEthereumBridgeRouter.t.sol
- Adds a couple of fuzzing and unit tests
- Break large unit tests into more specific scenarios
> test: revisit tests for Accountants

- packages/contracts-bridge/contracts/test/TokenRegistry.t.sol
- packages/contracts-ops/contracts/test/RebootTokenRegistry.t.sol
> feat(contracts-ops): tokenRegistry fork tests

- packages/contracts-core/contracts/test/Home.t.sol
want to test that only updater can submit updates
add test for !updater sig
> test: not updater sig

- packages/contracts-ops/README.md
make clear what setup actions need to be taken by grouping them; add invocation
> touchup readme

- packages/sdk-bridge/src/backend.ts
- packages/sdk/README.md
- packages/sdk/src/messageBackend/goldsky.ts
- packages/sdk/tests/index.test.ts
- packages/sdk/tests/message.test.ts
We implemented separation between environments in Goldsky, so this PR sets SDK to utilize that functionality.
> Different envs separated in SDK

- packages/contracts-ops/contracts/test/RebootEthereumBridgeRouter.t.sol
Simple fork test ensures that the bridge can approve and the accountant can transferFrom. This test checks that no token weirdness prevents the bridge router from approving, or the approval from working
Defense in depth against outside token state breaking accountant/bridge communication
> Sanity test for token approvals
