- packages/sdk-bridge/src/BridgeContracts.ts
- packages/sdk/src/CoreContracts.ts
rather than duplicating info in the constructor, we make an accessor for the deployheight
> fix: deployHeight uses a getter

- packages/new-deploy/src/DeployContext.ts
- packages/new-deploy/src/bridge/BridgeContracts.ts
- packages/new-deploy/src/core/CoreContracts.ts
- don't re-deploy existing replica proxies for already-deployed chains
- prevent multiple replica beacons & implementations from being deployed due to concurrency
- don't re-deploy bridge router
- don't re-deploy custom tokens
- don't re-appoint governor if deployer key is rightful governor
- don't re-enroll bridge router
- don't re-enroll governance router
- skip further checks if no watchers to enroll
> fix deploy: don't re-deploy or re-enroll

- package.json
- packages/new-deploy/scripts/deploy.ts
Closes #116 
@anna-carroll Reproduced the issue above following these steps
- removing the entire kovan object from the core object in `new-deploy/development/config.json`
- running `yarn new-deploy deploy`
I confirmed that `pushVerification` is working as expected. The reason the `verification.json` output file was empty is due to the way that `JSON.stringify` works with `Map`, the verification map needed to be converted to an object first otherwise it will appear empty.
Also added a helper script to run deploys from the monorepo root.
> fix: convert verification map to object before logging to output file

- packages/new-deploy/package.json
- packages/new-deploy/scripts/check.ts
- packages/new-deploy/src/Contracts.ts
- packages/new-deploy/src/DeployContext.ts
- packages/new-deploy/src/bridge/BridgeContracts.ts
- packages/new-deploy/src/core/CoreContracts.ts
- packages/new-deploy/src/index.ts
- packages/new-deploy/tests/index.test.ts
- yarn.lock
`DeployContext.asNomadContext` appears to not be registering providers properly in the returned context. This PR simplifies registration logic in an attempt to fix it
Iterate over entries instead of keys to avoid type confusion
> fix: better iteration in asNomadContext

- packages/multi-provider/changelog.md
- packages/multi-provider/package.json
- packages/multi-provider/src/contracts.ts
- packages/multi-provider/src/utils.ts
- packages/multi-provider/tests/index.test.ts
- packages/sdk-bridge/changelog.md
- packages/sdk-bridge/package.json
- packages/sdk-bridge/src/BridgeContext.ts
- packages/sdk-bridge/src/BridgeContracts.ts
- packages/sdk-govern/package.json
- packages/sdk-govern/src/GovernanceMessage.ts
- packages/sdk-govern/src/index.ts
- packages/sdk/changelog.md
- packages/sdk/package.json
- packages/sdk/src/CoreContracts.ts
- packages/sdk/src/NomadContext.ts
- packages/sdk/tests/index.test.ts
- yarn.lock
remove complicated and brittle reconnection logic in the sdks
- SDK packages now follow the same pattern as the new deploy package
- Contract object now pull a connection from the context on demand, rather than caching a reference to it
> refactor: un-complicate sdk connection logic

- packages/deploy/.npmignore
- packages/multi-provider/.npmignore
- packages/new-deploy/.npmignore
- packages/sdk-bridge/.npmignore
- packages/sdk-govern/.npmignore
- packages/sdk/.npmignore
we're currently npm publishing files that are useless or damaging to library installers
npmignore 'em 😎 
- [n/a] Added Tests
- [n/a] Updated Documentation
- [n/a] Updated CHANGELOG.md for the appropriate package
> chore: npmignore tsconfig files

- packages/new-deploy/src/core/CoreContracts.ts
There is a bug in the deploy script which causes Replica contracts to be initialized with the current root for the wrong Home contract.
Get the correct set of Core contracts for the Home before querying the current root
> fix: initial root for replica

- packages/new-deploy/changelog.md
- packages/new-deploy/config/development/overrides.json
Deploy script currently breaks when estimating gas on Goerli. 
Adds override block to `overrides.json` for Goerli. Script can now run to completion.
> fix: include goerli overrides in new-deploy

- packages/sdk/changelog.md
- packages/sdk/src/CoreContracts.ts
- packages/sdk/src/NomadContext.ts
- packages/sdk/tests/index.test.ts
- yarn.lock
Closes #156
`getReplica` on NomadContext only accepts domain number where everything else accepts nameOrDomain
Pass in nameOrDomain, resolveDomain
> bug: get replica name or domain

- packages/new-deploy/src/bridge/BridgeContracts.ts
Fix a bug in the deploy script populating governance transactions
don't pass `overrides` to `populateTransaction`
> fix: remove overrides for populateTransaction

- packages/keymaster/changelog.md
- packages/keymaster/src/keymaster.py
Watchers not being funded on replica chains.
Add watchers to list of agents that need funding on replica chains.
> fix: add watcher to keymaster replica fund set

- packages/new-deploy/config/overrides-production.json
- packages/new-deploy/src/core/CoreContracts.ts
- milkomeda overrides were throwing, need to be removed
- "home" was more confusing naming in deploy script, making it harder for developers to understand
- remove the overrides for milkomeda
- rename home -> remote in deploy script
> fix: overrides for milkomeda + rename home -> remote

- packages/multi-provider/changelog.md
- packages/multi-provider/package.json
- packages/new-deploy/changelog.md
- packages/new-deploy/package.json
- packages/sdk-bridge/changelog.md
- packages/sdk-bridge/package.json
- packages/sdk-govern/changelog.md
- packages/sdk-govern/package.json
- packages/sdk/changelog.md
- packages/sdk/package.json
multi-provider was not updated and published sp the current sdk package uses an outdated version of multi-provider. sdk-bridge and sdk-govern also affected since they rely on sdk.
publish multi-provider and re-publish sdk, sdk-bridge, sdk-govern. semver will enforce in the future once we're not using release candidate versioning (eg v0.0.1-rc.1)
> release: bump multi-provider, sdk, sdk-bridge, sdk-govern + update changelogs

- packages/new-deploy/src/bridge/BridgeContracts.ts
Deploy script transfers ownership of token registry to governance; it should be transferred to bridge router
- modify deploy script to transfer ownership fo token registry to bridge router
- modify deploy script checks to check the correct state
> fix: token registry owner

- packages/new-deploy/README.md
- packages/new-deploy/changelog.md
- packages/new-deploy/package.json
- packages/new-deploy/scripts/deploy.ts
- packages/sdk-bridge/package.json
- packages/sdk-govern/package.json
- packages/sdk-govern/src/index.ts
- packages/sdk/package.json
- packages/sdk/tests/index.test.ts
- yarn.lock
when deploy fails, you have to start from scratch again. we want to save the deployed contracts in the config and the verification inputs so we can restart gracefully
closes #115 
wrap the deploy invocation in a try/catch and cache the config and verification when it fails
> feature: restart-safe deploys

- packages/new-deploy/README.md
- packages/new-deploy/scripts/verify.ts
- README only included instructions for using published configuration environments; didn't include local config
- Verification console.log printed name & address of contracts, but now which network they were deployed on, making it difficult to check contract on Etherscan afterwards
- add local config option to README
- print network in verification flow in addition to contract name + address
> Update verification README + improve console.logs

- packages/new-deploy/changelog.md
- packages/new-deploy/scripts/deploy.ts
- packages/new-deploy/src/DeployContext.ts
DeployContext was built with Object-Oriented pattern in mind, however, governance transactions (CallBatches) were returned in a functional manner. This made more flexible changes adding new governance transactions more difficult.
Refactor to store the CallBatch on the DeployContext object.
> refactor: store `CallBatch` on `DeployContext`

- packages/sdk/changelog.md
- packages/sdk/src/NomadContext.ts
- packages/sdk/src/messages/NomadMessage.ts
Closes #134 
Adds process method to the sdk
We should make this more accessible for other applications using our sdk. Decided to add to NomadContext so any messages could be processed, not just Bridge messages.
- Fetch transaction details from Indexer API
- Fetch proof from S3
- Ensure signer is registered
- Call `proveAndProcess` on Replica
> add: process method on NomadContext

- packages/sdk/CHANGELOG.md
- packages/sdk/src/events/fetch.ts
- yarn.lock
paginated event querying was not updated with the new configuration layout, so querying would never use pages. this breaks most domains
Use the new config layout in `fetch.ts`
> fix: paginate with new config

- packages/sdk/src/messages/NomadMessage.ts
We want to use the message object to check for s3 proofs. 
Add a getter for the filename
Potential TODOs:
- add an async function to attempt to retrieve the proof? cc @ErinHales @Imti 
- add the bucket URI stem to the config format? cc @ltchang2019
> feature: convenience getter for s3 filename

- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/package.json
- packages/sdk-bridge/src/BridgeContext.ts
Expose the unsigned transaction, for allowing bridging using fireblocks wallet
Enable partners to bridge using fireblocks
Add `prepareSend` and `prepareSendNative` that expose the unsigned tx
> add: prepare sends

- packages/contracts-core/contracts/Home.sol
There must be a mechanism to transition the state from Failed to Active state in order to recover from proven Fraud.
Transition the Home from Failed to Active when the fraudulent Updater has been rotated for a new Updater.
> [QSP-1] un-fail Home in setUpdater

- packages/contracts-bridge/contracts/BridgeRouter.sol
- packages/contracts-bridge/contracts/BridgeToken.sol
- packages/contracts-bridge/contracts/TokenRegistry.sol
- packages/contracts-core/contracts/NomadBase.sol
- packages/contracts-core/contracts/UpdaterManager.sol
- packages/contracts-core/contracts/XAppConnectionManager.sol
- packages/contracts-core/contracts/governance/GovernanceRouter.sol
We do not want ownership of governable contracts to be renounced.
Make renounceOwnership a no-op
> [QSP-17] make renounceOwnership a no-op

- packages/contracts-core/contracts/Home.sol
- packages/contracts-core/contracts/NomadBase.sol
- packages/contracts-core/contracts/Replica.sol
- packages/contracts-core/contracts/test/TestCommon.sol
- packages/contracts-core/contracts/test/TestHome.sol
- packages/contracts-core/contracts/test/TestReplica.sol
The xApp is in control of determining when to block a Replica contract. The security layer for blocking fraud is at the xAppConnectionManager, in the hands of the xApp.
Additionally, we are moving in a direction where the concept of a `doubleUpdate` - and therefore, proving Fraud on the Replica - are irrelevant.
Remove `doubleUpdate` proofs and ability to transition to FAILED state from the Replica.
> [QSP-2] remove FAILED state from Replica

- packages/contracts-core/contracts/libs/Queue.sol
The `queue.contain` on Home scans for an item from first to last. In the case of a very long queue, when looking for an item at the end of the queue, the transaction could run out of gas. 
Search the queue from last to first instead. The Updater signs recent roots, so this mitigates the likelihood that the queue is too long to find the root.
> [QSP-4] reverse order of search in queue.contains

- packages/contracts-bridge/contracts/BridgeMessage.sol
- packages/contracts-bridge/contracts/BridgeRouter.sol
- packages/contracts-bridge/contracts/test/TestBridgeMessage.sol
Fast liquidity feature was mostly a proof of concept, which was not in use in production.
We are choosing to deprecate it.
> [QSP-8, QSP-10, QSP-11] deprecate fast liquidity send path

- packages/contracts-core/contracts/Replica.sol
- packages/contracts-core/contracts/test/TestReplica.sol
- packages/deploy/src/bridge/BridgeContracts.ts
- packages/deploy/src/core/CoreContracts.ts
- yarn.lock
In our original protocol design, we wanted message processing to be attempted exactly once, regardless of whether the subsequent `handle` call to the app reverted.  To guarantee this, we had to introduce some complexity to our Replica contracts: 
1. introduced gas-awareness to the protocol (with fields like `PROCESS_GAS`) to ensure that a malicious processor could not under-gas a transaction to cause it to fail
2. did some bespoke engineering like `ExcessivelySafeCall.sol` to ensure that the call could not be made to fail maliciously in other ways
These pieces of engineering introduced some challenges, such as: 
1. gas awareness made it more complicated to deploy on chains with different gas metering, like Optimism and Arbitrum, and brittle to upgrades that change gas metering, such as …
> [QSP-34] don't mark messages as Processed when they fail

- packages/contracts-core/contracts/Replica.sol
We wish to add some reasonable input validation to the optimisticSeconds field
Ensure optimisticSeconds is greater than 25 minutes & less than 1 year.
> [QSP-9, QSP-20] add bounds to optimisticSeconds

- packages/contracts-core/contracts/Replica.sol
- packages/contracts-core/contracts/test/TestReplica.sol
- packages/sdk/CHANGELOG.md
- packages/sdk/src/messages/NomadMessage.ts
Currently if a message is proven under a fraudulent root, it can eventually be processed even if the root is deleted from the confirmAt mapping by governance action. This means that the governance would need to clean each fraudulent message individually
- instead of storing a messagestatus enum, prove stores the root that was calculated for the proof
- process checks that the root is acceptable again before dispatch
- for backwards compatibility `MessageStatus.Proven` is hardcoded as an acceptable root.
- we now allow re-proving a message under a new root. This ensures that VALID messages proved under an INVALID root can be processed after fraud recovery
- This SHOULD NOT break storage as we simply change the semantics of a mapping, rather than the storage layout
- This WILL require …
> fix: prevent messages rendered invalid during recovery from eventually being processed

- packages/contracts-core/contracts/libs/Queue.sol
We revert the PR, as we weren't happy with the mitigation. 
We intend to remove root ordering in the near future, but due to the complexity of the endeavor (in both designing a solution and upgrading the system), we will PR the removal at a later time.
> Revert PR #299 (QSP-4)

- .gitignore
- .gitmodules
- scripts/install-deps.sh
- use `no-git` option when install libraries with forge
- Add `lib`. to `.gitignore`
- If `install-deps.sh` script doesn't find the dependencies, or if the dependency directory is empty, it will proceed to install it via `forge install`, pinned at a specific version
-
> fix: install dependencies

- packages/keymaster/src/keymaster.py
- packages/keymaster/src/utils.py
- Quick fix, could not fund neontesnet agents due to gas being too low.
- Fixed error `TypeError: Transaction had invalid fields: {'value': 5e+17}`
> Fix keymaster errors on neontestnet and arb-rinkeby networks

- packages/contracts-bridge/CHANGELOG.md
- packages/contracts-bridge/index.ts
- packages/contracts-bridge/tsconfig.json
- packages/contracts-core/CHANGELOG.md
- packages/contracts-core/index.ts
- packages/contracts-core/tsconfig.json
- packages/contracts-router/CHANGELOG.md
- packages/contracts-router/index.ts
- packages/contracts-router/tsconfig.json
- packages/tsconfig.package.json
Allow downstream users to identify the contract version via the contract TS packages
Future work may want to know whether it's using a compatible contract version. E.g. deploy script running updates may wish to know that it's on a later version than the previous contract version
export `version` at the root level of each contract package
> feat: Export version from TS package

- packages/sdk/CHANGELOG.md
- packages/sdk/src/NomadContext.ts
Help devs diagnose config fetching issues
If fetch falls back to a builtin config, it `console.warn` logs the error that caused fallback
> fix: fetch warns on failure

- packages/sdk-govern/CHANGELOG.md
- packages/sdk-govern/scripts/executeGovernorDomain.ts
In the script used to execute governance actions, if the caller provided a signing key which was not equal to the governor address, the script was a no-op but appeared to succeed. This behavior was easy to cause a caller to mistakenly believe they had successfully executed the transactions.
Add informative errors for any case in which the provided signing key is not equal to the governor address.
1. if the governor is a contract, point the caller to Gnosis (future: submit tx directly via Gnosis) 
2. if the governor is an EOA but the provided key is incorrect, inform the caller
> fix: execute script silent no-op if contract or bad key

- packages/contracts-bridge/contracts/BridgeMessage.sol
- packages/contracts-bridge/contracts/BridgeRouter.sol
- packages/contracts-bridge/contracts/interfaces/IConnext.sol
Allow Connext to be integrated directly into the `BridgeRouter` instead of migration.
- Add a reference to `Connext` to the `BridgeRouter`
- Add a `bytes32 _externalId` to the `BridgeMessage`. This identifier will only be set for Connext transfers
- Add a new `Type` for `BridgeMessage` of `ConnextTransfer`, which will include a non-zero identifier, and empty recipient
- Add `xsend` method to be used by Connext. This method acts exactly like `send`, but will create a `ConnextTransfer` message (recipient will be destination domain Connext contract, which is stored on the `BridgeRouter` so is empty within the message and there is a 32 byte identifier).
- On `handle` if it is a `ConnextTransfer` message, it will mint funds to the stored Connext contract and call `reconcile` with the external …
> feat: add connext reconciliation + sending

- .github/workflows/indexer-docker.yml
- packages/indexer/CHANGELOG.md
- packages/indexer/package.json
/version endpoint wasn't returning a commit sha which is super helpful for debugging and knowing exactly which commit is deployed.
Pass commit sha as build arg to github actions docker/build-push-action step
> Fix version endpoint on indexer api

- .github/workflows/tests.yml
- CONTRIBUTING.md
Add cache step. 
If no newer version of the cli is released, it takes ~1s. 
If there are newer versions (should be very rare), it will build and then cache.
> feat: Fix long CI due to accumulator-cli

- foundry.toml
- packages/contracts-core/contracts/test/Home.t.sol
- packages/contracts-core/contracts/test/Replica.t.sol
- packages/contracts-core/contracts/test/utils/MerkleTest.sol
less meaningless terminal output on builds
Remove unused variables from tests, 
Adds a foundry ignore for a spurious warn re: constructor visibility
Add a foundry ignore for an intentional departure from compiler recommendation
- unfortunately, this won't silence hardhat's compilation warnings
- [n/a] Added Tests
- [n/a] Updated Documentation
- [n/a] Updated CHANGELOG.md for the appropriate package
> chore: fix compiler warnings

- packages/sdk/CHANGELOG.md
- packages/sdk/src/messages/NomadMessage.ts
New protocol versions return the root a message was proven under. We should capture and expose this in the TS SDK
Change MessageStatus from an enum to a union with discrimanator.
This is an API-breaking change (major version bump) however, given that we are in RCs this is still a candidate for the current non-RC release (i.e. we don't need to bump to 3.0.0 as 2.0.0 is not finalized)
> refactor: change message status from enum to tagged union

- packages/contracts-core/CHANGELOG.md
- packages/contracts-core/contracts/Replica.sol
Ensure a call to `proveAndProcess` doesn't fail if frontrun by a `prove` call
Shortcut the prove call if the message has been proven under an acceptable root
> fix: proveAndProcess now allows process-only usage

- packages/keymaster/CHANGELOG.md
- packages/keymaster/package.json
- packages/keymaster/src/account.ts
- packages/keymaster/src/config.ts
- packages/keymaster/src/keymaster.ts
- packages/keymaster/src/kms/index.ts
- packages/keymaster/src/retry_provider/provider.ts
- yarn.lock
I have added this fields to config. If there is an ignore field there are 3 sub-fields all , local , remote . If an agent role name (lets say watcher) happen to appear in:
all then remote and local watchers not working anymore
local  then local watchers not working
remote  guess what happens...
Noteworthy, kathy  or updater  can appear only in the local network. I don't care right now.
also, hardcoded bank threshold to 4 eth, as we don't want to have 20+ eth in the bank
> Keymaster: Ignore agents for particular networks

- packages/deploy/src/bridge/BridgeContracts.ts
- packages/deploy/src/core/CoreContracts.ts
If contracts were previously enrolled for a remote domain, the deploy script does not execute governance transactions to change the router.
Fix the condition which skips enrolling routers to ensure that the correct router is enrolled (rather than no router enrolled).
> fix: enroll BridgeRouter and GovernanceRouter if re-deployed

- packages/keymaster/CHANGELOG.md
- packages/keymaster/src/account.ts
- packages/keymaster/src/index.ts
- packages/keymaster/src/keymaster.ts
Right now keymaster runs nets one by one sequentially, to make it easier to debug. But, we see that it is quite stable, though if there are many networks it takes lots of time to till one net at the end of the queue will get checked and paid.
Now we want all nets to have their own loop.
It spins up one "task" per network and the task spins until it breaks in a try-catch loop until an unhandled promise rejection happens, which is impossible to catch anyways.
> Make keymaster run networks in parallel (concurrently)

- packages/deploy/scripts/deploy.ts
- packages/deploy/src/DeployContext.ts
The deploy script would often fail without throwing an error by hanging indefinitely after submitting a transaction. In this case, if a developer killed the process to re-start the deploy script, the partial config & verification outputs would not be written to a file, meaning that the deploy process would have to restart from scratch and throw away the contracts deployed during the previous run. 
Output the config & verification to a file each time it's possible after contracts are deployed, so a developer can kill the process any time if a transaction is hanging
> feat: output config & verification each time new contracts are deployed

- packages/deploy/scripts/deploy.ts
- packages/deploy/src/DeployContext.ts
Deploy checks threw a compile error because no value was provided for `outputdir` when instantiating `DeployContext`
Add a default value for `outputdir` if not explicitly supplied
> fix: add default value for outputdir

- packages/contracts-bridge/contracts/BridgeMessage.sol
- packages/contracts-bridge/contracts/BridgeRouter.sol
- packages/contracts-bridge/contracts/interfaces/IBridgeHook.sol
- packages/contracts-bridge/contracts/test/BridgeMessage.t.sol
Routers that build on top of Nomad Home need to authenticate the sender of the message is a valid Router on the other chain. Similarly, Routers that build on top of Nomad BridgeRouter need to do the same.
Add the sender of the tokens + message on the origin chain to the TransferToHook message format.
> feat: add token sender to TransferToHook message

- packages/contracts-bridge/CHANGELOG.md
- packages/contracts-bridge/hardhat.config.ts
- packages/contracts-core/CHANGELOG.md
- packages/contracts-core/hardhat.config.ts
- packages/contracts-router/CHANGELOG.md
- packages/contracts-router/hardhat.config.ts
prevent HH from barfing on scripts' use of forge
> fix: filter scripts from hh compilation

- packages/contracts-ops/CHANGELOG.md
- packages/contracts-ops/contracts/CallBatch.sol
Allow forktests to prank scripts
Add prank() and prankRecovery() to the CallBatch
These will execute the callbatch against governance, when running in anvil
> feature: prankable callbatch

- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/src/BridgeContext.ts
Preflighting recover calls will not work if `from` is not set
set from in the prepare method
> fix: populateRecover sets from for proper gas estimation

- packages/sdk/tests/message.test.ts
This test breaks when domain numbers change.
Dynamically set the domain bytes
> fix: dynamic message test

- packages/contracts-bridge/contracts/test/TokenRegistry.t.sol
(from slack, by James)
- the input has domain == localDomain
- the input id has non-empty top bytes, so it passes the vm.assume
- the input id has empty bottom 20 bytes, so getLocalAddress shows the local address as 0
- this triggers the if block in ensureLocalToken, and deploys a new registry token
- ensureLocalToken returns the new token, which is not equal to the lower 20 bytes of the input
this is a condition of use violation. The token registry assumes that there is no local token at address(0), and therefore, the code assumes that it’ll never get a local token ID with empty bottom 20 bytes
Ensure in the test that the ID is formatted correctly, which means that the lower 20 bytes should be != 0
> fix: properly formatted tokenId

- packages/contracts-ops/contracts/scripts/Reboot.s.sol
- packages/contracts-ops/contracts/scripts/UpgradeCallBatches.s.sol
- without vm.broadcast, transactions don't send
- using `call` instead of `staticcall` was sending 6 transactions on-chain
> fix reboot for script running

- packages/contracts-ops/contracts/CallBatch.sol
Indepedent, may be merged before or after any other PR
> fix: callbatch does not revert on empty batches

- packages/contracts-ops/contracts/Config.sol
- packages/contracts-ops/contracts/test/utils/INomadProtocol.sol
- want to be able to go from domain number to domain name in Config.sol 
- fix: domains are uint32 not uint256
- feat: getDomainName
> feat: Config.getDomainName

- packages/contracts-ops/contracts/Config.sol
- packages/contracts-ops/contracts/test/Reboot.t.sol
- Fork tests intended to change two specific Updaters (Home and one Replica) in order to facilitate local signing of Updates
- Home updater was not being set anywhere, while Replica updater setting had a bug (`remote` variable was empty)
- however, Due to unexpected behavior in `vm.writeJson`, all updaters in the config were being overwritten - which caused the tests to pass anyway 
- this is not the expected or desired state
Fix the setup
- ensure `remote` is set first
- set only the two specific desired updaters
> fix: override updater properly in reboot setup

- packages/contracts-core/contracts/test/GovernanceRouter.t.sol
- packages/contracts-ops/contracts/test/Reboot.t.sol
If we run fork tests on other chains, the governance router tests need to function for both the governor domain and the non-governor domain
for non-governor domains,
- for `handle` tests, ensure the remote domain is `setUp` to the governor domain. the GovernanceRouter tests assume that the remoteDomain is the governor domain; on the actual governor domain, the tests just transfer to the remote domain; but for non-governor domains, this is not possible
- for `TransferGovernor` tests, don't assume homeDomain is the current governor domain.
> fix: governance tests work for governor and non-governor chains

- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/README.md
- packages/sdk-bridge/package.json
- packages/sdk-bridge/src/BridgeContext.ts
- packages/sdk-bridge/tests/index.test.ts
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
Deprecate staging
We shouldn't reference staging or support staging anywhere in sdk. Wasn't able to access testnet MockAccountant from development.
Replace references to staging with development, remove staging from choices of env.
> update: deprecate staging

- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
Bump sdk and sdk-bridge packages
sdk wasn't built before release causing errors in sdk-bridge
Bump and release both packages
> fix: release sdk first

- packages/sdk-bridge/CHANGELOG.md
- packages/sdk-bridge/package.json
- packages/sdk-bridge/src/BridgeMessage.ts
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
- packages/sdk/src/messageBackend/backend.ts
- packages/sdk/src/messageBackend/goldsky.ts
- packages/sdk/src/messages/NomadMessage.ts
Would like to get BridgeMessage from MessageHash as that is more precise and less prone to error
Add `baseFromMessageHash` and `bridgeFromMessageHash` methods
> add: get BridgeMessage from MessageHash
